### ISSUE TITLE
Do we need the file /proj/adszee/adslogging?

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/adslogging#5]

**Comment by jonnybazookatone** [comment]
The only *important* stuff may be the 'backups/' folder within adslogging/. This looks like it is the indexes from elasticsearch for certain days, from the ELK setup that Jay had running. If you want to keep it for someone to look at in the future, you can put this somewhere sensical.

The rest of the folder is just this repository, and given it is currently up to date with respect to the last commit, you should be able to delete it without any issues.

**Comment by aaccomazzi** [comment]
I removed the folder.
